# Numpy 101

The goal of this challenge is to get familiar with the Numpy library, manipulate multidimensional arrays and apply some linear algebra operations without using `for` loops.

💡 Do not forget to keep the [Numpy Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf) close during this challenge.

In [1]:
import numpy as np # Run this cell!

---

**Q1** - Create a null vector (i.e. with only zeros `0`) of size 10. 

It should look like this:

```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.zeros.html"><code>numpy.zeros</code></a></p>
</details>

In [1]:
# your code here
ten_zeros = ?

---

**Q2** - Create a vector with values from 5 to 10

It should look like this:

```
array([ 5,  6,  7,  8,  9, 10])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.arange.html"><code>numpy.arange</code></a></p>
</details>

In [2]:
# your code here
from_five = ?

---

**Q3** - Create the following matrix `A` as a NumPy `ndarray`:

$
A = 
\begin{pmatrix}
5 & 9 & 7\\
1 & 0 & 3
\end{pmatrix}
$

<br>
<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.array.html"><code>numpy.array</code></a></p>
    <p>Checkout more about the relationship between<a href="https://stackoverflow.com/questions/15879315/what-is-the-difference-between-ndarray-and-array-in-numpy"><code>numpy.array and nump.ndarray</code></a></p>
</details>

In [3]:
# your code here
A = ?

---
**Q4** - Create the following matrix `B` without using the `np.array()` constructor:

$
B = 
\begin{pmatrix}
1 & 1\\
1 & 1
\end{pmatrix}
$

In [4]:
# your code here
B = ?

---

**Q5** - Create a vector `lin_twenty` of 20 elements evenly spaced between `-1` and `1`.

It should look like this:

```
array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.linspace.html"><code>numpy.linspace</code></a></p>
</details>

In [5]:
# your code here
lin_twenty = ?

---

**Q6** - Create a 3x3 identity matrix `C`:

$
C = 
\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.eye.html"><code>numpy.eye</code></a></p>
</details>

In [6]:
# your code here
C = ?

---

**Q7** - Reshape the following `ndarray` `D` into a 2x3 matrix `E`:

$
D = 
\begin{pmatrix}
2 & 9 & 7 & 3 & 1 & 5
\end{pmatrix}
$
    
$
E = 
\begin{pmatrix}
2 & 9 & 7\\
3 & 1 & 5
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.reshape.html"><code>numpy.reshape</code></a></p>
</details>

In [7]:
# your code here
D = ?
E = ?

---

**Q8** - Create a 8x8 checkboard matrix `F`:

$
F = 
\begin{pmatrix}
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.tile.html"><code>numpy.tile</code></a></p>
</details>

In [8]:
# your code here
F = ?

---

**Q9**: Select the second column of this `ndarray` `G` and reshape it as an `ndarray` of 4 lines and 1 column `reshaped_G`:

$
reshaped\_G = 
\begin{pmatrix}
0.?\\
0.?\\
0.?\\
0.?\\
\end{pmatrix}
$

In [9]:
G = np.random.random((4, 5))
print(G)

In [10]:
# your code here
reshaped_G = ?

---

**Q10** - Compute the sum of matrixes `G` and `H` and store the result into a variable `gh_sum`:

$
G = 
\begin{pmatrix}
0 & 4\\
-4 & -3\\
1 & 1
\end{pmatrix}
$

$
H =
\begin{pmatrix}
0 & 1\\
1 & -1\\
2 & 3
\end{pmatrix}
$

$
G + H = ?
$


In [11]:
# your code here
gh_sum = ?

### Check your code!

In [ ]:
from nbresult import ChallengeResult

result = ChallengeResult('numpy',
    ten=ten_zeros,
    from_five=from_five,
    A=A,
    B=B,
    lin_twenty=lin_twenty,
    C=C,
    E=E,
    F=F,
    reshaped_G=reshaped_G,
    gh_sum=gh_sum
)
result.write()
print(result.check())